repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [-l 79]
        language_version: python3.11

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [
                "--rcfile=.pylintrc",
                "./src"
        ]